### PR TITLE
Proposal for adding version metadata to header section

### PR DESCRIPTION
**Pull request by ghandic**

### CODE REVIEW

**Comment by ghandic** [comment]
Could be an additional flag similar to the timestamp

Allows for

```
# generated by datamodel-codegen 0.16.1:
#   filename:  example.yml
#   timestamp: 2023-01-26T01:11:51+00:00
```

**Comment by koxudaxi** [comment]
@ghandic
Thank you for creating the PR.
Looks good 😄 
But I don't want to affect existing users.
We should apply the changes with the new CLI option.

**Comment by ghandic** [comment]
Agreed, just an initial PR to gauge appetite 😄

**Comment by ghandic** [comment]
I've added it similar to the timestamp, lmk thoughts

**Comment by ghandic** [comment]
Looks good ⭐  thanks!

**Comment by koxudaxi** [comment]
@ghandic 
I have released a new version `0.17.0`
The version has the option.
Thank you very much!!

**Pull request merged**
