### PR TITLE
Add `$ref` support to schemas

### PR DESCRIPTION
**Pull request by ytoml**
Hi, I'm a newbie to OpenAPI and this generator.
This generator doesn't seem to have `$ref` resolving at `schemas`, thus I added.
I would help us keep Yamls separated and easier to manage.

### CODE REVIEW

**Comment by koxudaxi** [comment]
@ytoml 
Thank you for creating the PR.
We can't assign `Reference Object` to `schemas` object directly.
We should define `Reference Object` as the value of `Map`.

`schemas | Map[string, Schema Object | Reference Object]`
https://spec.openapis.org/oas/v3.0.0#fixed-fields-5

**Comment by ytoml** [comment]
Thank you for information!
Why I thought it valid first was because `swagger-cli bundle` did expand `$ref` at `schemas`.  Then, `swagger-cli`'s implementation seems to be wrong...? (or it fits some legacy specification?).

**Comment by ytoml** [comment]
Anyway, closing this PR, thanks!

**Comment by koxudaxi** [comment]
I can't find the rule in the old specification.
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md

> swagger-cli's implementation seems to be wrong...?

`swagger-cli` may support json pointer anywhere :thinking:

**Pull request closed without merging**
