### PR TITLE
Fix allOf with common prefix and $ref

### PR DESCRIPTION
**Pull request by azatoth**
Per #714 test is needed to examplify the issue.

### CODE REVIEW

**Comment by koxudaxi** [comment]
@azatoth 
Thank you for creating this PR.
I added some lines to fix the problem.

**Comment by azatoth** [comment]
> @azatoth Thank you for creating this PR. I added some lines to fix the problem.

Thank you :) I didn't know what the underlying issue was, but I thought at least I could add a test to exemplify the issue.

**Comment by koxudaxi** [comment]
@azatoth 
I explain the problem.
1. the code generator wants to create a new class inherited allOf's schemas.
2. The class name is made with a field name. `foo_bar` ->  `FooBar`
3.  the case doesn't create a new class because the schema is one.
4. The generator decides the class name of `FooBar` schema 
5. `FooBar` is reserved as the same name as another schema name. 
6. The generator changes the name to `FooBar1`

**Comment by azatoth** [comment]
@koxudaxi Thanks for the explanation; now it makes perfectly clear what the underlying issue was.

**Comment by koxudaxi** [comment]
@azatoth 
I have released the new version as 0.14.1 :smile:

**Pull request merged**
