### PR TITLE
fix: parsing external relative ref that contains a local ref

### PR DESCRIPTION
**Pull request by Niraj-Kamdar**
Closes: #714

### CODE REVIEW

**Comment by koxudaxi** [comment]
@Niraj-Kamdar 
Thank you for creating the PR.
I would review your PR.
Could you please revert the package name?

**Review by koxudaxi — CHANGES_REQUESTED** [review]
Could you please revert the package name?

**Comment by Niraj-Kamdar** [comment]
Ah sorry for that, I kept it same as where I deployed the fixed package but forgot to revert it back while opening PR, will make the changes.

**Comment by koxudaxi** [comment]
@Niraj-Kamdar 
Thank you for pushing it.
But, Your commitment broke the existing unit test. 
Could you fix it?

**Comment by koxudaxi** [comment]
@Niraj-Kamdar 
In the current master branch, the problem is fixed.
https://github.com/koxudaxi/datamodel-code-generator/pull/964

Thank you very much

**Pull request closed without merging**
