### PR TITLE
refactoring parse logic

### PR DESCRIPTION
**Pull request by koxudaxi**
- fix template filename
- refactoring parse logic
- fix template

### CODE REVIEW

**Comment by joshbode** [comment]
I've just merged this locally if you want me to push it somewhere

**Comment by koxudaxi** [comment]
@joshbode 
 Thank you, I will try it soon.

**Comment by koxudaxi** [comment]
@joshbode
Thank you. I just merged.

**Comment by joshbode** [comment]
great!

**Pull request merged**
