### PR TITLE
handle edge-case where models map to the __init__.py level of a module

### PR DESCRIPTION
**Pull request by joshbode**
Sorry to follow up with a fix so soon after the previous PR - but as the branch name sez: `modules-are-hard` :)

### CODE REVIEW

**Comment by joshbode** [comment]
Thank you!

**Comment by koxudaxi** [comment]
I have released it as `0.4.4`!!

**Comment by koxudaxi** [comment]
I know it is difficult to treat modular.
Thank you very much.

**Comment by joshbode** [comment]
I keep finding new edge-cases as my use-cases evolve :)

**Pull request merged**
