### PR TITLE
Fix merging config and args

### PR DESCRIPTION
**Pull request by mahdilamb**
Currently the config and args don't combine if they are sequences or dictionaries. This serves to fix that

### CODE REVIEW

**Comment by koxudaxi** [comment]
@mahdilamb 
Thank you for creating the PR.
The unittest failed. Could you please fix it to keep the current behavior?

**Comment by mahdilamb** [comment]
Will do in the next few days! A bit busy at the moment, but it's on my radar!

**Comment by mahdilamb** [comment]
@koxudaxi that should be everything fixed

**Comment by koxudaxi** [comment]
@mahdilamb
I'm sorry for the late reply.
Thank you very much!!

**Pull request merged**
