### PR TITLE
switch away from deprecated pydantic method

### PR DESCRIPTION
**Pull request by iliakur**
I'm starting with just one method conversion to get initial feedback and check tests, but there's also one lurking in `types.py` which I'll convert later in the same PR.

### CODE REVIEW

**Comment by koxudaxi** [comment]
Thank you for creating PR.
Could you please add the condition of `PYDANIC_V2` ?
Because, we should support v1 in runtime yet.
https://github.com/koxudaxi/datamodel-code-generator/blob/24bb074eda4354c254fc96c81d6242965af817a1/datamodel_code_generator/parser/jsonschema.py#L164-L175

**Comment by koxudaxi** [comment]
@iliakur 
I just added `def model_rebuild(cls...` to DataType :wink: 

Thank you very much!!

**Comment by iliakur** [comment]
@koxudaxi Thanks for the final tweaks! qq: when do you think this will be released?

**Comment by koxudaxi** [comment]
@iliakur 
You can install the version from pypi via pip.
I'm sorry I didn't announce the released 
https://github.com/koxudaxi/datamodel-code-generator/releases/tag/0.21.4

**Comment by iliakur** [comment]
oh, this is great, thanks a bunch for such a quick release!!

**Pull request merged**
