### PR TITLE
Add aliases option to map reserved fields

### PR DESCRIPTION
**Pull request by joshbode**

### CODE REVIEW

**Comment by koxudaxi** [comment]
@joshbode 
Thank you for creating this PR.

I have some requests.
1. Would you please fix unit tests? Travis CI does not show any errors on PR :thinking: 
https://travis-ci.org/github/koxudaxi/datamodel-code-generator/builds/710951779

2. Would you update README and documents?
https://github.com/koxudaxi/datamodel-code-generator/blob/master/README.md
https://github.com/koxudaxi/datamodel-code-generator/blob/master/docs/index.md

**Comment by joshbode** [comment]
oops - sorry - it helps if I add the new files :)

**Comment by koxudaxi** [comment]
@joshbode 

I have released a new version as `0.5.18` :tada: 

Thank you very much :smile:

**Comment by joshbode** [comment]
Thank you for the merge, @koxudaxi :)

**Pull request merged**
