### PR TITLE
improve merge of CLI arguments and pyproject options

### PR DESCRIPTION
**Pull request by joshbode**
- only pick up CLI arguments if they've been set, otherwise use pyproject value (or default)
- make sure relative filenames work
- perform some config type-conversion in validators

### CODE REVIEW

**Comment by koxudaxi** [comment]
@joshbode 
Thank you for fixing my code.
It was broken. I'm sorry :cry: 

I probably should not work at midnight.

**Comment by joshbode** [comment]
no worries! you got excited ;)

it was an easy fix, although I got _very_ stuck on the failing tests... pytest was hiding the real reason for failures due to issues with changing directory, so I used the `chdir` context-handler which seems to work better :)

**Comment by koxudaxi** [comment]
I will use the function next time :wink: 

BTW, Travis-ci didn't notify an error on this PR.
https://travis-ci.org/github/koxudaxi/datamodel-code-generator/jobs/714341637

I will change CI to GitHub action.

**Comment by koxudaxi** [comment]
@joshbode 

I have fixed some problems.
https://github.com/koxudaxi/datamodel-code-generator/pull/192

I have published it as `0.5.24`

Thank you very much.

**Pull request merged**
