### PR TITLE
Don't generate enum models that have been swapped by a reused model

### LINKED ISSUE #429: Enum models swapped with a reused model are still generated
**Describe the bug**
When using `--reuse-model`, a cached version of a similar model might be used. In these cases, for enums, the references to the original model are swapped to a reference to the cached model. However, the original models are still getting generated, even though they are not used anywhere anymore (as references to them have been swapped to the cached model).

**To Reproduce**

Example schema:
```yaml
openapi: 3.0.0
info:
  version: 0.0.1
  title: Foo API
paths:
  /foo:
    get:
      responses:
        "200":
          description: Getting foo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Foo"
  /bar:
    get:
      responses:
        "200":
          description: Getting bar
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bar"
components:
  schemas:
    Foo:
      properties:
        my_enum:
          type: string
          description: very interesting description
          enum:
            - VALUE_A
            - VALUE_B
            - VALUE_C
    Bar:
      properties:
        my_enum:
          type: string
          description: very interesting description
          enum:
            - VALUE_A
            - VALUE_B
            - VALUE_C
```

Used commandline:
```
$ datamodel-codegen --input duplicate-enums.yaml --output duplicate-enums.py --reuse-model
```

This will generate the following file:
```python
class MyEnum(Enum):
    VALUE_A = 'VALUE_A'
    VALUE_B = 'VALUE_B'
    VALUE_C = 'VALUE_C'

class Foo(BaseModel):
    my_enum: Optional[MyEnum] = Field(None, description='very interesting description')

class MyEnum1(Enum):
    VALUE_A = 'VALUE_A'
    VALUE_B = 'VALUE_B'
    VALUE_C = 'VALUE_C'

class Bar(Foo):
    pass
```

**Expected behavior**
Enum models that have been swapped by a model that is reused should not be generated, as they are not used anymore.

The output should look like this:
```python
class MyEnum(Enum):
    VALUE_A = 'VALUE_A'
    VALUE_B = 'VALUE_B'
    VALUE_C = 'VALUE_C'

class Foo(BaseModel):
    my_enum: Optional[MyEnum] = Field(None, description='very interesting description')

class Bar(Foo):
    pass
```

**Version:**
 - OS: Gentoo
 - Python version: 3.7.10, 3.8.9
 - datamodel-code-generator version: 0.11.5

Let me know if this isn't clear enough

### PR DESCRIPTION
**Pull request by shnups**
When looking for model to reuse, pin a list of enum models that have been swapped; them remove them after the fact.

Fixes #429

### CODE REVIEW

**Comment by koxudaxi** [comment]
@shnups 
Thank you for creating this PR and [another one](https://github.com/koxudaxi/datamodel-code-generator/pull/427).

I have merged these PRs and released a new version `0.11.4` :rocket: 

Thank you very much :bow:

**Comment by shnups** [comment]
Thanks for the quick reviews and release @koxudaxi 
Could you also push the new release to pypi? Thank you !

**Comment by koxudaxi** [comment]
@shnups 

> Could you also push the new release to pypi? Thank you !

Oh, I'm sorry. I had pushed a new release as `0.11.5`.
But, GitHub Action is stopping. https://github.com/koxudaxi/datamodel-code-generator/actions

**Comment by shnups** [comment]
Ops, I missed that, sorry. I also have some CI queued on my side.
Wait and see I guess :)

**Comment by koxudaxi** [comment]
@shnups 
I have re-pushed and released it  as `0.11.5` :rocket: 
https://pypi.org/project/datamodel-code-generator/0.11.5/

Thank you very much.

**Comment by shnups** [comment]
Awesome, all good!
Thanks

**Pull request merged**
