### PR TITLE
Update poetry.lock

### PR DESCRIPTION
**Pull request by fsecada01**
Raise `jsonschema` version to 4.2.0 or greater

### CODE REVIEW

**Comment by fsecada01** [comment]
Raise minimum `openapi-spec-validator` version to 0.3.8; rebuilt `poetry.lock` to fulfill new requirements.

**Comment by fsecada01** [comment]
@koxudaxi : this should ameliorate the dependency conflicts that arise when using this alongside jupyter notebooks/lab.

**Comment by koxudaxi** [comment]
@fsecada01 
I'm sorry for my late reply.
I can update the maximum version. But, I don't want to change the minimum version to avoid breaking the existing system.
Why should we need to change the version?

**Comment by koxudaxi** [comment]
I want to merge the PR. And I revert the minimum version to keep the current dependency.
If you need to upgrade to the minimum version, please tell me again.

**Comment by yhack** [comment]
I'm trying to use OpenAPI spec version 3.1 and this update to the max version of openapi-spec-validator is exactly what I need. Thank you! Looking forward to its release.

**Comment by koxudaxi** [comment]
@fsecada01 
Thank you for creating PR.

@yhack
I have released the new version as 0.14.1 :tada:

**Pull request merged**
