### PR TITLE
feat: support InputFileType.Json and InputFileType.Dict

### PR DESCRIPTION
**Pull request by XieJiSS**
This PR fixes supports for `InputFileType.Json` and `InputFileType.Dict`.

`RAW_DATA_TYPES` is defined as:

```python
RAW_DATA_TYPES: List[InputFileType] = [
    InputFileType.Json,
    InputFileType.Yaml,
    InputFileType.Dict,
    InputFileType.CSV,
    InputFileType.GraphQL,
]
```

Currently, the code handles them in a `if input_file_type in RAW_DATA_TYPES:` branch. Due to the `else:` branch being too loose, only `InputFileType.CSV` and `InputFileType.Yaml` can be correctly parsed. Other input data types will be treated as `InputFileType.Yaml` and hence triggering exceptions.

PR tested locally using the following code:

```python
from pathlib import Path
from tempfile import TemporaryDirectory

from datamodel_code_generator import DataModelType, InputFileType, generate

with TemporaryDirectory() as temporary_directory_name:
    temporary_directory = Path(temporary_directory_name)
    output = Path(temporary_directory / "model.py")
    generate(
        { "foo": 1, "bar": { "baz": 2 } },
        input_file_type=InputFileType.Dict,
        input_filename="placeholder",
        output=output,
        output_model_type=DataModelType.PydanticV2BaseModel,
        snake_case_field=True,
    )
    model: str = output.read_text()

print(model)
```

Original traceback:

```python
Traceback (most recent call last):
  File "~/Library/Caches/pypoetry/virtualenvs/parser-ycrm5vgb-py3.12/lib/python3.12/site-packages/datamodel_code_generator/__init__.py", line 375, in generate
    obj = load_yaml(
          ^^^^^^^^^^
  File "~/Library/Caches/pypoetry/virtualenvs/parser-ycrm5vgb-py3.12/lib/python3.12/site-packages/datamodel_code_generator/__init__.py", line 53, in load_yaml
    return yaml.load(stream, Loader=SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/Library/Caches/pypoetry/virtualenvs/parser-ycrm5vgb-py3.12/lib/python3.12/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
             ^^^^^^^^^^^^^^
  File "~/Library/Caches/pypoetry/virtualenvs/parser-ycrm5vgb-py3.12/lib/python3.12/site-packages/yaml/cyaml.py", line 26, in __init__
    CParser.__init__(self, stream)
  File "yaml/_yaml.pyx", line 288, in yaml._yaml.CParser.__init__
TypeError: a string or stream input is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/Code/python/parser/parser/script/test.py", line 8, in <module>
    generate(
  File "~/Library/Caches/pypoetry/virtualenvs/parser-ycrm5vgb-py3.12/lib/python3.12/site-packages/datamodel_code_generator/__init__.py", line 381, in generate
    raise Error('Invalid file format')
datamodel_code_generator.Error: Invalid file format
```

After applying this patch:

```python
# generated by datamodel-codegen:
#   filename:  placeholder
#   timestamp: 2024-11-12T06:50:33+00:00

from __future__ import annotations

from pydantic import BaseModel


class Bar(BaseModel):
    baz: int


class Model(BaseModel):
    foo: int
    bar: Bar
```

Reference:

https://github.com/koxudaxi/datamodel-code-generator/blob/f5c8852176270a3f01eb78a116140ab8cf26f853/datamodel_code_generator/__init__.py#L355..L381

### CODE REVIEW

**Comment by XieJiSS** [comment]
Looks like some tests are failing - will have a deeper look tomorrow.

**Comment by XieJiSS** [comment]
I've submitted a new commit which should have fixed the failing test.

**Comment by XieJiSS** [comment]
hmmmmm... Should I modify test cases to trigger the `raise Error('Invalid file format')` branch (I don't think this can be done without explicit type casting to `Any`), or should I just add a `# noqa` instead?

**Comment by koxudaxi** [comment]
> hmmmmm... Should I modify test cases to trigger the raise Error('Invalid file format') branch (I don't think this can be done without explicit type casting to Any), or should I just add a # noqa instead?

We should try to add the test case if it's not diffcult.

**Comment by koxudaxi** [comment]
@XieJiSS Will you write the unittest? or Should I pick up the task? 
I would release a new version this weekend.

**Comment by XieJiSS** [comment]
> @XieJiSS Will you write the unittest? or Should I pick up the task? I would release a new version this weekend.

Roger that, I'm trying to add a new test. If it goes smoothly I'll add another commit in ~1 hour, and if I met difficulties I'll come back and report it here.

**Comment by XieJiSS** [comment]
I've added a test for the direct dictionary input feature. My local `pytest` result shows all tests are passing / skipped.

**Comment by koxudaxi** [comment]
@XieJiSS we should cover all cases.

https://app.codecov.io/gh/koxudaxi/datamodel-code-generator/pull/2165?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr+comments&utm_term=Koudai+Aono#a915ac0b4adaa1565e6e2b0af8c35e34-R389

**Comment by XieJiSS** [comment]
Hi @koxudaxi, I checked the codecov report and noticed that there's a "partial" warning flag for the Dict branch. I think my test case should have covered this branch - it tests direct dictionary input with input_file_type set to InputFileType.Dict. And there's already another test case which test InputFileType.Dict + path to file as input. IMO together they should have covered all possible cases of this branch? Not sure what I've missed here.

**Pull request merged**
