### PR TITLE
Add option to convert all con* annotations to Field constraint options

### PR DESCRIPTION
**Pull request by joshbode**
Add option to convert all `con*` annotations (e.g. `constr(max_length=64)`) to `Field` constraint options (e.g. `pydantic.Field(..., max_length=64)`)

### CODE REVIEW

**Comment by koxudaxi** [comment]
@joshbode 
I think this PR is a great idea :tada: 
I have released a new version as `0.5.14`

Thank you very much.

**Comment by joshbode** [comment]
Thanks!
I was trying to avoid https://github.com/samuelcolvin/pydantic/issues/156

**Comment by koxudaxi** [comment]
@joshbode 
Interesting.
Pydantic may have to support [PEP 593](https://www.python.org/dev/peps/pep-0593/) or improve mypy plugin in pydnatic package.

I used the new option for private projects daytime.
It works fine for me :smile: 
Thank you.

**Comment by ofek** [comment]
Is this still relevant for v2?

**Comment by koxudaxi** [comment]
@ofek 
Yes.
I added the unittest for v2.
Do you meet any problem?
https://github.com/koxudaxi/datamodel-code-generator/blob/8691002196fdd5162801eca266019aad8a95fb19/tests/test_main.py#L797-L841
https://github.com/koxudaxi/datamodel-code-generator/blob/8691002196fdd5162801eca266019aad8a95fb19/tests/data/expected/main/main_with_field_constraints_pydantic_v2_use_standard_collections/output.py
https://github.com/koxudaxi/datamodel-code-generator/blob/8691002196fdd5162801eca266019aad8a95fb19/tests/data/expected/main/main_with_field_constraints_pydantic_v2_use_generic_container_types/output.py

**Comment by ofek** [comment]
Thanks no problem I was just wondering if this option would still be applicable since version 2 removed some stuff

**Pull request merged**
