### PR TITLE
update isort and black

### PR DESCRIPTION
**Pull request by Chilipp**
Hey @koxudaxi!

very nice package, thanks a lot for your work on this! I'd like to use it and I am already using the latest version of isort and black. It would be nice if the datamodel-code-generator is compatible with this which is whiy I make this PR.

From my perspective, this PR can be merged if the CI passes.

### CODE REVIEW

**Comment by Chilipp** [comment]
hmm ok. the CI is failing because a new version of `black` is installed. But to me, this is actually rather a CI issue and does not justify to force the users of this package to install an old version of `black`.

not sure what would be the best to fix this. One option would be to create a venv in [`lint.sh`](https://github.com/koxudaxi/datamodel-code-generator/blob/master/scripts/lint.sh) to make sure that the correct version of black and isort is installed

```bash
#!/usr/bin/env bash

set -e

python -m venv lint
source lint/bin/activate

pip install black==19.10b0 "isort>=4.3.21,<5.0"

black --check datamodel_code_generator tests
isort --check-only datamodel_code_generator tests

deactivate
rm -r lint

mypy datamodel_code_generator

```

what do you think @koxudaxi?

**Comment by koxudaxi** [comment]
@Chilipp 
Thank you for creating this issue.
I understand your suggestion.
But, some users want to keep the old version of dependence packages.
we talked about the problem.
https://github.com/koxudaxi/datamodel-code-generator/issues/195
Can you support the old version too?

I have checked your PR.
A related code of isort is changed.
I would we can check the version before run sort.
```python
if isort.__version__.startswith('4.'): 
   return SortImports(file_contents=code).output
else:
   return isort.code(code) 
```

> not sure what would be the best to fix this. One option would be to create a venv in lint.sh to make sure that the correct version of black and isort is installed

I think the change is good :+1:

**Comment by Chilipp** [comment]
> I would we can check the version before run sort.

alright, done with https://github.com/koxudaxi/datamodel-code-generator/pull/251/commits/cc25f6966811c4653b35801d2dc22829bf4ac942

> I think the change is good +1

ok, see https://github.com/koxudaxi/datamodel-code-generator/pull/251/commits/6a2397cee7b3c507f70ded066b9c0b00e8cf8edd

**Comment by Chilipp** [comment]
alright, the same problem now with `test.sh` and `test.bat`. I'd fix this with something like

```bash
#!/usr/bin/env bash
set -e

python -m venv venv

source venv/bin/activate
pip install -e .[all] isort==4.3.21 "black>=19.10b0,<20"

pytest --cov=datamodel_code_generator --cov-report term-missing tests

deactivate
rm -r venv
```

what do you think @koxudaxi ?

**Comment by koxudaxi** [comment]
@Chilipp 
I think your approach is good :rocket:

**Comment by Chilipp** [comment]
alright, seems to work @koxudaxi :smile: I am done here, merge it if you like

Thanks a lot again for your work on this =)

**Comment by koxudaxi** [comment]
I just came up with a good approach.
If `list.sh` have to change arguments of isort by versions, we can check the isort version in the shell scripts and use the `if` statement. 

I may change the shell scripts.

Thank you very much.

**Comment by Chilipp** [comment]
sorry, I can't really follow, but do what you think is the best @koxudaxi :sweat_smile:

**Comment by koxudaxi** [comment]
No problem. I was too late getting the idea :sweat_smile: 
I will release tonight:rocket:

**Comment by Chilipp** [comment]
awesome! thanks a lot =)

**Comment by koxudaxi** [comment]
@Chilipp 
I have released a new version as `0.6.3`

**Pull request merged**
